---
- name: Download Tomcat
  get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_ver }}/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
     dest: /tmp/apache-tomcat-{{ tomcat_ver }}.tar.gz
     owner: tomcat
     group: tomcat

- name: Extract tomcat archive
  unarchive:
    src:  /tmp/apache-tomcat-{{ tomcat_ver }}.tar.gz
    dest: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    creates: /usr/share/tomcat/bin
