---
- name: install pre req
  apt:
    name:
      - wget
      - git
      - default-jdk
    state: present
- name: ensuring directory
  file:
      name: /opt/tomcat
      state: directory
- name: download tomcat.tar
  get_url:
        url: http://mirror.23media.de/apache/tomcat/tomcat-8/v{{tomcat_ver}}/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
        dest: /opt/tomcat/
- name: extract
  unarchive:
      src: /opt/tomcat/apache-tomcat-{{tomcat_ver}}.tar.gz
      remote_src: true
      dest: /opt/tomcat
- name: permissions
  shell: cd /opt/tomcat/apache-tomcat-{{tomcat_ver}}/bin && chmod 777 startup.sh shutdown.sh catalina.sh
- name: download sample
  get_url:
      url: https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/sample.war
      dest: /opt/tomcat/apache-tomcat-{{tomcat_ver}}/webapps/
- name: start apache
  shell: nohup /opt/tomcat/apache-tomcat-{{tomcat_ver}}/bin/catalina.sh start
