--- 
- name: Installing mysql 
  apt:
   name: [' libmysqlclient-dev', 'mysql-server', 'mysql-client', 'python3-mysqldb']
   state: present
   update_cache: true

- name: Starting mysql
  service:
   name: mysql
   state: started
   enabled: yes
